# Generated by Django 3.2.8 on 2021-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomprice_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra_prices', to='rooms.Room', verbose_name='ΔΩΜΑΤΙΟ'),
        ),
    ]
