# Generated by Django 3.2.8 on 2021-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomprice_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprice',
            name='value_type',
        ),
        migrations.CreateModel(
            name='RoomCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('capacity', models.BooleanField(default=False)),
                ('room_price', models.ManyToManyField(to='rooms.Room', verbose_name='ΕΠΙΠΠΛΕΟΝ ΧΡΕΩΣΕΙΣ')),
            ],
        ),
    ]
