# Generated by Django 3.2.8 on 2021-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20211114_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcharge',
            name='room_price',
        ),
        migrations.AddField(
            model_name='roomcharge',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.Room', verbose_name='ΕΠΙΠΠΛΕΟΝ ΧΡΕΩΣΕΙΣ'),
        ),
    ]
