# Generated by Django 3.2.8 on 2021-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20211114_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='ΜΕΓΙΣΤΗ ΧΩΡΗΤΙΚΟΤΗΤΑ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_value_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΕΠΙΠΛΕΟΝ ΚΟΣΤΟΣ ΑΝΑ ΑΤΟΜΟ'),
        ),
    ]
