# Generated by Django 3.2.8 on 2021-11-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='charges_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΕΠΙΠΛΕΟΝ ΧΡΕΩΣΕΙΣ'),
        ),
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='reservations.reservation')),
            ],
        ),
    ]
