# Generated by Django 3.2.8 on 2021-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20211117_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='charges',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
