# Generated by Django 3.2.8 on 2021-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20211120_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracharge',
            name='charges',
            field=models.IntegerField(default=1, verbose_name='ΧΡΕΩΣΕΙΣ'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΑΞΙΑ'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΑΞΙΑ ΜΟΝΑΔΑΣ'),
        ),
    ]
