# Generated by Django 3.2.8 on 2022-02-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_payment_in_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_in_advance',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
