# Generated by Django 3.2.8 on 2021-11-12 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('repeater', models.BooleanField(default=False)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220, verbose_name='Ονοματεπώνυμο')),
                ('identity', models.CharField(blank=True, max_length=220, null=True, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=220, null=True, verbose_name='ΤΗΛΕΦΩΝΟ')),
                ('passport', models.CharField(blank=True, max_length=220, null=True, verbose_name='ΔΙΑΒΑΤΗΡΙΟ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='ΗΜΕΡΟΜΗΝΙΑ ΔΙΕΥΘΥΝΣΗΣ')),
                ('address', models.CharField(blank=True, max_length=220, null=True, verbose_name='Διεύθυνση κατοικίας')),
                ('country', models.CharField(default='Ελλάδα', max_length=220, verbose_name='Εθνικότητα')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΥΠΟΛΟΙΠΟ')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, verbose_name='Σημειώσεις')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό')),
                ('date', models.DateField(default=datetime.datetime(2021, 11, 12, 13, 53, 45, 540344, tzinfo=utc))),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.paymentmethod')),
            ],
        ),
    ]
