# Generated by Django 3.2.8 on 2021-11-12 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 15, 9, 31, 241723, tzinfo=utc)),
        ),
    ]
