# Generated by Django 3.2.8 on 2021-11-17 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 5, 38, 42, 47043, tzinfo=utc)),
        ),
    ]
