# Generated by Django 3.2.8 on 2021-11-20 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customerpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 20, 6, 20, 19, 789513, tzinfo=utc)),
        ),
    ]
