# Generated by Django 3.2.10 on 2022-02-17 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customerpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 12, 33, 59, 44739, tzinfo=utc)),
        ),
    ]
