# Generated by Django 3.2.8 on 2022-02-18 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20220218_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 18, 5, 20, 58, 574238, tzinfo=utc)),
        ),
    ]
