# Generated by Django 3.2.8 on 2022-02-18 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20220218_0900'),
        ('customers', '0015_alter_customerpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 18, 7, 0, 40, 159606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation'),
        ),
    ]
